### PR TITLE
Accept configuration instead of hard-coded

### PR DESCRIPTION
**Pull request by joksnet**
Excellent project, excellent service. I would like to host my own instance and the hard-coded configuration make it difficult and unmaintainable. What about passing the service configuration as default and allow to run it's own instance with it's own configuration? I think a better patch for this could be done, but the moment this will help to someone trying to setup their self-hosted service.

### CODE REVIEW

**Comment by kanasite** [comment]
Awesome project. Would appreciate more if some variables like max email size limit and sender limit throttling can be configured rather than hardcoded too.

**Comment by soyuka** [comment]
This looks good to me, just needs a fix on the tests. I have the same needs and I'm going to try this branch.

**Comment by joksnet** [comment]
Moved to #67.

**Comment by niftylettuce** [comment]
#67 is now merged

**Pull request closed without merging**
